### ISSUE TITLE
"-bash: _completion_loader: command not found" error

### ISSUE THREAD

**Issue by sdondley** [cykerway/complete-alias#10]
On macOS, I was getting this error. I had bash-completion version 1.3.3 installed with homebrew. Uninstalling the old version and reinstalling v2 with `brew install bash-completion@2` fixed the issue.

I'll supply a doc patch to mention this fix.

**Comment by cykerway** [comment]
The brew formulae `bash-completion` is meant to support bash 3.2. And bash 4.1+ users need to use `bash-completion@2`. Good to point it out. Merged. Thank you very much.
