### ISSUE TITLE
issue on complete

### ISSUE THREAD

**Issue by bobbyben** [cykerway/complete-alias#13]
Hi

After install, i got this message when i attempt to auto_complete a command when i press "tab".
`-bash: compgen: warning: -C option may not work as you expect`

I'm using ubuntu 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Comment by willpower232** [comment]
what command are you trying to complete?

**Comment by bobbyben** [comment]
I've found the problem. I had to clean complete list file because some lines had "-C" option, which is not compatible whit my os.

Thanks
