### ISSUE TITLE
Make available as package

### ISSUE THREAD

**Issue by dannysauer** [cykerway/complete-alias#16]
I generally dislike checking GitHub for updates of software I use.  This is just a single file, but never the less, it's exceptionally useful and I'd like my package manager to handle keeping it up to date with any future changes. :)

To that end, I used the OpenSUSE Open Build Service to set up a project hosting the build of packages, and assembled a spec file for generating RPMs on SUSE and RedHat/Fedora.  If there's interest, I'll also do the Debian/Ubuntu packaging at the same place (I make more RPMs recently, so that's where I started).  I have it set up for my fork to automatically trigger builds upon creation of a new tag, but I'd be more than happy to shift maintainership over to this project so I can kill the automation which syncs my fork.  It's just a matter of adding a webhook to the GitHub project with a token (I'll share mine if no one here wants to create an openbuild account) and continuing to use tags for new releases; I've done the rest of the work to automatically build packages and generate the changelog (PR coming).  If that's not something of interest, that's ok - I'll just keep mirroring the project to my own fork. :)

The resulting packages (and OS-appropriate repositories) are available at https://software.opensuse.org/package/bash-complete-alias.

**Comment by cykerway** [comment]
I understand the pain of tracking updates from upstream, but the packaging is better left to maintainers who do this specific job. I am not able to maintain spec files for multiple distros at the same time. Even if I do, the spec files I write may not look good to them and the packages generated from my spec files will not be signed with their keys. This is a matter in downstream and I can do little.

Well, the way I deal with this kind of 3rd-party software is to write my own spec file and keep it my own. That's what you do now.

**Comment by dannysauer** [comment]
Understood. It'd be nice if third parties could simply subscribe to to push notifications on repo update instead of needing the repo owner to set it up, but that's more of a github gripe than anything. :D

**Comment by cykerway** [comment]
TBH I don't know how the notification works, but someone just caught me when I was rewriting a git tag. My guess is a watched repo will send push notifications to watchers as soon as there is a new release, but I'm not sure how that connects to an automatic package build. If you know any about that, you are welcome to post it below, which would be helpful for package maintainers.

**Comment by dannysauer** [comment]
You can get emails on a number of things from watches, but webhooks can (currently) only be added by an organization or repository owner. Anyone else needs to poll for changes. Which is easy enough to do; a scheduled github action can fairly easily run to check for changes.

One example is https://github.com/marketplace/actions/fork-sync, which allows someone to create a fork and then generate their own webhook events when their fork is auto-updated oby the scheduled aaction.  here are other similar actions for the same general kind of workaround. :)
