### ISSUE TITLE
README documentation minor suggestions

### ISSUE THREAD

**Issue by mralusw** [cykerway/complete-alias#17]
Wonderful project. Some comments on documentation:

* it's not clear from the README whether this works for multi-word aliases (such as `alias apti='apt install'`). In fact, it does, which is very nice, and should perhaps be mentioned in the description / examples
* the README suggests "appending" `complete_alias` to `~/.bash_completion` (presumably, after everything that's already in there). And then  adding some more completions (separated from the initial ones by the `complete_alias` code blob). Perhaps it makes more sense to insert `complete_alias` at the top of the file, or, better yet, source it from the cloned `git` repo, as the user may want to get updates

Also, there is a way to install `complete_alias` for all visible aliases which might also be interesting for users:
```
complete -F _complete_alias $(alias | perl -lwne 'print $1 if /^alias ([^=]+)=/')
```

**Comment by lucaspar** [comment]
The complete_alias for all aliases is really useful, it definitely should be in the readme!

**Comment by cykerway** [comment]
Thanks for the suggestions. The really-useful one-liner has been added in the README!
