### ISSUE TITLE
Partial failure with $() in alias

### ISSUE THREAD

**Issue by fcantournet** [cykerway/complete-alias#2]
if I define the following aliases :
```
alias ldocker='docker run -it -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -u $(id -u $USER):$(id -g $USER)'
alias marcel='docker run -it -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -u 1000:1000'
```

the `marcel` alias autocomplete works flawlessly :+1: for both flags and for arguments (specifically in this case I can autocomplete docker image names)

However in the case of the `ldocker` alias only flag autocomplete seems to work (both the flag names and the possible arguments for the flags)
normal arguments (as image names) do not autocomplete

changing the `$()`  to a ` syntax doesn't solve the problem, so it probably has to do evaluating in the alias definition?
Is this forbidden somehow?

**Comment by cykerway** [comment]
Hello,

Thank you for your feedback!

It's not forbidden. It's a limitation of the old way of word breaking. We were doing word breaking using xargs, which is simple and effective for most use cases. But it's simply not good enough in your case. In fact it gives wrong word breaking in this example.

Therefore I spent some time implementing a new word breaking routine, tested it against your case and several other cases. I think the new routine solves your problem and is in general better than the old one.

Specifically, I tested with the following aliases and the updated script is able to complete both flags and arguments:

    alias ldocker='docker run -u $(id -u $USER):$(id -g $USER)'
    alias marcel='docker run -u 1000:1000'

Simply download [version 1.5.0](https://github.com/cykerway/complete-alias/releases/tag/v1.5.0) and you are good to go.

Please let me know whether it solves your problem and whether new problem occurs. Thank you.

**Comment by fcantournet** [comment]
Wow, that was fast ! Amazing !

Just tested it and it works great.
Thanks a lot !
