### ISSUE TITLE
Git tag rewrite

### ISSUE THREAD

**Issue by tinywrkb** [cykerway/complete-alias#21]
Hi @cykerway,

I packaged and maintained the complete-alias AUR package for easy installation and update on Arch LInux.  
As 
I would highly appreciate that git tags would not be rewritten and break checksumming of the fetched tarball. Please tag a new release instead. It can be a patch release (MAJOR.MINOR.PATCH).

**Comment by cykerway** [comment]
Good point. I should really sum up all the changes then make a single release. But you are a hardworking maintainer: Today is Saturday and you reported the issue within hours. Tag `1.9.0` will not change any more.

**Comment by tinywrkb** [comment]
Thanks for the prompt reply.
