### ISSUE TITLE
It doesn't  work

### ISSUE THREAD

**Issue by puraminy** [cykerway/complete-alias#22]
I did all you said in a ubuntu 16.0 but when I type an alias and hit tab simply nothing happens, except for showing all available command which I had before this too.

**Comment by puraminy** [comment]
Sorry, it seems that it's working. I just misunderstood the purpose of this function. I was looking for something that when I have an alias for example `alias foo=bar`, wherever I type `foo` and hit tab, it automatically replace `foo` with `bar`. If you know anything like that you may introduce it to me.

**Comment by cykerway** [comment]
Nope. I have never seen a function in bash that can do that kind of replacement. Not sure if you can do it in other shells.

There is something *like* that, but I don't know why it's useful:

    _foo () {
        echo -ne "\b\b\b\bbar"
    }
    alias foo="bar"
    complete -F _foo foo

**Comment by puraminy** [comment]
> Nope. I have never seen a function in bash that can do that kind of replacement. Not sure if you can do it in other shells.
> 
> There is something _like_ that, but I don't know why it's useful:
> 
> ```
> _foo () {
>     echo -ne "\b\b\b\bbar"
> }
> alias foo="bar"
> complete -F _foo foo
> ```

I tried you function, it works if `foo` is the only typed string after command prompt. In fact I wanted to replace some long paths using such aliases for example consider:

```
alias large=/home/pouramini/models/t5/larage/
```
and then use in a command like this:

```
cp finetune.py large
```
now I would like when I hit tab after large it replaces it with my target directory I introduced with aliases. There could be other solutions except using alias though.

**Comment by cykerway** [comment]
I guess that's impossible using alias. Define a variable instead.

    large=/home/pouramini/models/t5/larage/
    cp finetune.py "$large"
