### ISSUE TITLE
Doesn't handle ':' in alias name

### ISSUE THREAD

**Issue by mralusw** [cykerway/complete-alias#25]
I have
```
alias p:='declare -p'
complete -F _complete_alias p:
```

yet TAB won't complete variable names. `p.`, `p?` work. `complete -v p:` also works. Not sure if due to `complete_alias` or `bash-completion`.

**Comment by willpower232** [comment]
I think you'll find colon is already used by bash for other things so there is probably some confusion behind the scenes

**Comment by cykerway** [comment]
The colon is in alias name, not its body. So I guess this isn't a problem of `complete-alias`.

I suggest you try this (works on my machine):

    COMP_WORDBREAKS=${COMP_WORDBREAKS//:}

If you want to know why, read this: https://tiswww.case.edu/php/chet/bash/FAQ

>   E13) Why does filename completion misbehave if a colon appears in the filename?

But I suggest not to use special characters such as colons. Stay safe with alphanumerics wherever possible.
