### ISSUE TITLE
_completion_loader: command not found

### ISSUE THREAD

**Issue by ryanberckmans** [cykerway/complete-alias#26]
Hi,

On Ubuntu 21.04 with `apt install bash-completion`,

When invoking my alias I'm getting

```
_completion_loader: command not found
_command_offset: command not found
```

afaik, these utils should be provided as part of bash-completion. What am I doing wrong? Thanks.

**Comment by cykerway** [comment]
Yes they are provided by package `bash-completion` but for some reason you are not sourcing them. Actually I wonder if you can even complete non-alias commands.

I guess what you should do is to check `/etc/profile`, `~/.bashrc`, `~/.bash_profile`, etc. to make sure one of them is sourcing the file `bash_completion` provided by package `bash-completion`.

Failing that, you could download [the file](https://raw.githubusercontent.com/scop/bash-completion/master/bash_completion) from its git repo and source the downloaded file instead.

**Comment by ryanberckmans** [comment]
Thanks! I was rebuilding my dev environment and didn't realize that `bash-completion` wasn't being sourced.
