### ISSUE TITLE
multi commands alias 

### ISSUE THREAD

**Issue by Mark-Joy** [cykerway/complete-alias#28]
Hello,
Thank you for your useful script. I have an issue as the below:

```
alias apti="apt install"
alias pkgi="apt update && apt install"

```

```
λ [~] $ apti
Display all 1507 possibilities? (y or n)
λ [~] $ pkgi

```
apti \<tab>: showing the possible packages for installation

pkgi \<tab>: nothing shows

Is it possible to support this case?

**Comment by cykerway** [comment]
Would you like to test your commands with the latest commit at https://github.com/cykerway/complete-alias/commit/0086ad7f1d97b39d6fe1d4225aa0d08607b88f3d and tell me how it works?
