### ISSUE TITLE
Slow sourcing time

### ISSUE THREAD

**Issue by SuperSandro2000** [cykerway/complete-alias#29]
Before adding this my bashrc took roughly 200ms to load. With this enabled for 6 aliases it takes roughly 600ms which is a bit much for my liking. Do you think this could be improved?

**Comment by cykerway** [comment]
It's likely some [recent changes](https://github.com/cykerway/complete-alias/commit/84be7d22dd96d6fa58d670ba7a094992ae98daf2) slow it down. Sourcing can take about 500ms.

If you need some quick solution, rollback before that commit.

If you are using the latest commit and happen to understand how it works, you can comment out `__compal__save_vanilla_cspecs` and put something in `__compal__set_vanilla_completion_custom`.

I will follow up when I figure out what's the right thing to do here.

**Comment by cykerway** [comment]
If you check out https://github.com/cykerway/complete-alias/commit/7e034e3ab3b4ef05d09124d10d22c3bc12fcadf0 and put this before sourcing the script:

    export COMPAL_AUTO_UNMASK=0

Then the sourcing time should be trivial, like 5ms, not 500ms.

This somewhat invalidates the major change that slows it down while keeping other useful updates. Working out the real optimization may take some time as I feel it's not that trivial.

**Comment by cykerway** [comment]
To keep things simple, I disabled the problematic feature in version [1.17.0](https://github.com/cykerway/complete-alias/tree/1.17.0).

So just check out that version and use it as usual. The sourcing takes about 5ms. No special configuration needed.

**Comment by cykerway** [comment]
The feature is reworked in version [1.18.0](https://github.com/cykerway/complete-alias/tree/1.18.0). Now it is disabled by default, but can be enabled by setting an envar `COMPAL_AUTO_UNMASK=1` before sourcing the main script.

When disabling this feature, the sourcing time is about 5ms. When enabling it, the sourcing time is about 30ms (depending on how many command completions you have, tested with 100-200 completions). If sourcing time is important to you, my advise is to disable this feature.
