### ISSUE TITLE
'_complete_alias' not found

### ISSUE THREAD

**Issue by WillDeSnoo** [cykerway/complete-alias#31]
When pressing tab to complete an alias, bash throws an error:

bash: completion: function `_complete_alias' not found

**Comment by cykerway** [comment]
For whatever reason you didn't successfully source the file `complete_alias`.

Interactive test (should print the function body):

~~~bash
$ . complete_alias
$ declare -f _complete_alias
~~~

If the above interactive test is successful, check your `bashrc`, `bash_profile`, etc. You may need to restart the shell.

**Comment by WillDeSnoo** [comment]
I hadn't sourced it in .bashrc, thanks for your help!
