### ISSUE TITLE
Create a github release

### ISSUE THREAD

**Issue by marciomazza** [cykerway/complete-alias#33]
It looks like this repo has no github release.

I suggest to follow the steps on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

The created release should show up at
https://github.com/cykerway/complete-alias/releases

The latest release will be accessible at
https://github.com/cykerway/complete-alias/releases/latest

For comparison here are two github repos that do have releases:
https://github.com/mozilla/geckodriver
https://github.com/ryanoasis/nerd-fonts

**Comment by cykerway** [comment]
Thank you for the instructions but I prefer tags to releases. Why? Because I am too lazy. I'll reopen when I change my mind.
