### ISSUE TITLE
completion issues when alias contains a colon

### ISSUE THREAD

**Issue by jmmen1** [cykerway/complete-alias#35]
I have an alias that runs a docker container and mounts my work directory inside the container:

    alias dkrun='docker run -it --rm --volume $HOME/workdir:$HOME/workdir --workdir $HOME/workdir'

When I type `dkrun<TAB><TAB>` it should show a list of available images on my system, but **complete-alias** doesn't seem to like the `--volume` option because of the colon. If I remove the `--volume` option from the alias (or even just the colon), then the completion works as expected, and it displays the list of images.

hardware: MacBook Pro (16-inch, 2021) with Apple M1 Pro
OS: macOS Monterey version 12.4
GNU bash: version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)
bash-completion v2 installed using homebrew

I thought that maybe the Apple M1 Pro might be causing the issue, so I also tested the scenario inside a linux/amd64 container:

    docker run -it --rm --platform linux/amd64 --volume /var/run/docker.sock:/var/run/docker.sock ubuntu:focal

Inside the container, I installed **bash-completion**, **docker.io**, and **complete-alias**. Then I created the `dkrun` alias as before and sourced **.bash_completion**, but the completion still doesn't work when the alias contains a colon.

Incidentally, while the completion does not display the list of available images as expected, if I type `dkrun --<TAB><TAB>` then it does complete the list of long options available to the `docker run` command.

I used to have a MacBook Pro (16-inch, 2019) with Intel Core i7 and macOS Monterey, and completion worked fine.

**Comment by cykerway** [comment]
Colon could be a problem in `bash-completion`:

- https://github.com/scop/bash-completion Q. Completion goes awry when I try to complete on something that contains a colon.
- http://tiswww.case.edu/php/chet/bash/FAQ E13

Yet it could be a different problem in `complete-alias`:

- The colon `:` is a word separator.
- The backslash quoting `\` is minimally implemented.

So, while E13 suggests you to "quote the colon with a backslash", we suggest you to "quote the colon with double quotes":

    alias dkrun='docker run -it --rm --volume "$HOME/workdir:$HOME/workdir" --workdir "$HOME/workdir"'

**Comment by jmmen1** [comment]
Yes, quoting the colon with double quotes as you suggested seems to have fixed the issue.

Thanks!

**Comment by jmmen1** [comment]
I've changed the alias in my .bashrc as suggested, and the alias completion is working as expected.
