### ISSUE TITLE
alias 'eats' space on VS Code aliases

### ISSUE THREAD

**Issue by marcfedorow** [cykerway/complete-alias#36]
Info:
```bash
$ bash --version
GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)
# VS Code is installed and 'code' is a command to run it
```

Problem:
```bash
$ mkdir foo
$ cd foo
$ touch bar
$ code [tab] # transforms to "code bar "
$ alias code='code --goto'
$ complete -F _complete_alias code
$ source ~/.bash_completion.d/complete_alias
$ code [tab] # transforms to "code bar", no space at the end
```

I did not met any problems with any other aliased comands
(including vi, subl, etc that also have file[:line[:column]] or file[ +line] syntax).
So I think it is more VS Code's problem rather than this script's one.
Still if it may be somehow solved, it would be beautiful.

**Comment by cykerway** [comment]
https://github.com/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/resources/completions/bash/code#L18
