### ISSUE TITLE
doc: Clarify the way to enable `auto-unmask`

### ISSUE THREAD

**Issue by RoneoOrg** [cykerway/complete-alias#39]
Hi there,

to enable aliases auto-unmasking, the Readme just [says](https://github.com/cykerway/complete-alias#config):

> set `COMPAL_AUTO_UNMASK` to `1`

but the [last line of the script](https://github.com/cykerway/complete-alias/blob/master/complete_alias#L1060) also says:

> to complete all aliases, run this line after all aliases have been defined;
> #complete -F _complete_alias "${!BASH_ALIASES[@]}"

Which way is the right one?

(Thanks for this awesome tool BTW, it works perfectly fine with Debian 11 and ~ 140 aliases)

**Comment by cykerway** [comment]
These two statements are entirely different.

First of all, you can work with either "auto" or "manual" unmask. Setting `COMPAL_AUTO_UNMASK` to `1` is not required. The "auto" unmask is an optional feature. It is for situations where "manual" unmask does not work and users do not want to fix case by case. You probably should go with "manual" unmask unless you are sure that doesn't work in your situation.

OTOH statement `complete -F _complete_alias "${!BASH_ALIASES[@]}"` applies `_complete_alias` to all aliases that have been defined. It is a convenience to apply `_complete_alias` universally.

> Which way is the right one?

They are separate, so you can have each one on or off. Most users would leave `COMPAL_AUTO_UNMASK` at its default `0` and uncomment `complete -F _complete_alias "${!BASH_ALIASES[@]}"`.
