### ISSUE TITLE
"error: cannot unmask alias command:"

### ISSUE THREAD

**Issue by RoneoOrg** [cykerway/complete-alias#40]
Hi,

I face a bug when using `complete-alias` with aliases such as `alias mv='mv -i'`

### Install
- install bash-completion: `sudo apt install bash-completion`
- download `complete_alias` [from Github](https://github.com/cykerway/complete-alias/blob/master/complete_alias)
- paste in `~/.bashrc.d/completion-aliases.bashrc`
- source from `.bashrc`
- **enable auto unmask** with modifications of the lines `COMPAL_AUTO_UNMASK=1` and `complete -F _complete_alias "${!BASH_ALIASES[@]}"`

**At this point everything works fine**, auto unmasking works great.

### The bug

**The bug appears** when writing `mv ` then hitting `Tab`:

```bash
error: cannot unmask alias command: mv
error: cannot unmask alias command: mv
error: cannot unmask alias command: mv
error: cannot unmask alias command: mv
error: cannot unmask alias command: mv
error: cannot unmask alias command: mv
```

Note that the same issue happens with `alias rm='rm -i'` and `alias cp='cp -i'`

Any hint?

### Config

- Debian 11
- GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)

**Comment by cykerway** [comment]
The error was printed on https://github.com/cykerway/complete-alias/blob/master/complete_alias#L807

It means you are trying to complete an alias with `_complete_alias` which is not completed by `_complete_alias`. This is something very unlikely to happen. I can't quite recall a situation leading to this. My guess is you are sourcing files in wrong order.

My suggestions are:

1. Dump current completion function for `mv` using `complete -p mv` to make sure it is `_complete_alias`.
2. Double check your system and user bashrc and bash_profile to make sure you are sourcing `bash_completion` and `complete_alias` in the correct order. The correct order is as stated here. One way to enforce this order is to source `complete_alias` in `~/.bash_completion`, but this doesn't seem to be what you are doing. So you are on your own.
3. Make sure you source `complete_alias` very late in your bashrc, after all aliases have been defined.
4. Set `COMPAL_AUTO_UNMASK` to `0` to see if manual unmask works in this case.
5. If you really want to use auto unmask, there is a function `__compal__debug_raw_vanilla_cspecs` you can run to debug collected raw vanilla cspecs. Search for `mv` in its result and see if that's what you are looking for.

**Comment by RoneoOrg** [comment]
Thanks for your enlightment!

**It's fixed now**, the issue was a conflict with ` fzf_path_completion`.

Here is the way I fixed it, for later reference:

- run `complete -p mv`
- output: `complete -F _fzf_path_completion mv`
- search your bashrc files for `FZF_COMPLETION_DIR_COMMANDS`
- remove conflicting commands at `a_cmds=` to manage it with `complete-aliase`. In my case I removed `rm`, `cp`and `mv`
- reload your config files

Thanks a lot for taking the time to guide me to this solution!

**Comment by ju1ius** [comment]
Hi, I've just been bitten by this. 

Given the following alias:
```sh
alias ls="ls --color=auto"
```
Entering `ls -<TAB>` ran into an infinite loop of `error: cannot unmask alias command: ls` messages.

The fix for me was to ensure that:
1. `fzf` completions are sourced BEFORE `complete_alias` 
2. `COMPAL_AUTO_UNMASK` is activated

For example:
* In `~/.bashrc`:
    ```sh
    alias ls="ls --color=auto"
    source /etc/bash_completion
    ```
* In `~/.bash_completion`:
    ```sh
    source ~/.fzf.bash

    export COMPAL_AUTO_UNMASK=1
    source ~/.complete_alias
    complete -F _complete_alias "${!BASH_ALIASES[@]}"
    ```

With this setup, both fzf (`ls /etc/**<TAB>`) and complete_alias completions (`ls -<TAB>`) work.
