### ISSUE TITLE
Does not work with aliases with '--param='

### ISSUE THREAD

**Issue by Freedzone** [cykerway/complete-alias#8]
Hello.
Thank you for the script.

But i encountered 1 problem. Autocomplete does not work if alias has certain parameters, e.g
```shell
# works
alias ggrep='grep -riP'

# does not work
alias ggrep='grep --exclude-dir=.git'
```

**Comment by cykerway** [comment]
Hello,

Could you please give:

-   Your system environment: OS, Bash version and grep version.
-   Steps to reproduce the bug.
-   Expected and actual results.

Thank you

**Comment by cykerway** [comment]
It's actually more complicated than that. If you try:

    grep --context=10 --<Tab>

Then it does auto-complete the next option. When I was writing this script I had quite a few surprises ;)
